import { execa } from "execa";
import type { GitHubIssue } from "../machine/context.js";
import type { AutoDevConfig } from "../config/schema.js";

export async function createPullRequest(
  issue: GitHubIssue,
  config: AutoDevConfig,
): Promise<{ prUrl: string; prNumber: number }> {
  const title = `feat: #${issue.number} — ${issue.title}`;

  const body = config.git.pr_template
    .replace("{summary}", `Implements issue #${issue.number}: ${issue.title}`)
    .replace("{issue_number}", String(issue.number))
    .concat(`\n\n---\n*Generated by AutoDev*`);

  const result = await execa("gh", [
    "pr",
    "create",
    "--repo",
    config.repo,
    "--base",
    "main",
    "--title",
    title,
    "--body",
    body,
  ]);

  // Extract PR URL
  const output = result.stdout.trim() || result.stderr.trim();
  const urlMatch = output.match(/https:\/\/github\.com\/[^\s]+/);
  const prUrl = urlMatch ? urlMatch[0] : `https://github.com/${config.repo}/pulls`;

  // Extract PR number from URL
  const numberMatch = prUrl.match(/\/pull\/(\d+)/);
  const prNumber = numberMatch?.[1] ? parseInt(numberMatch[1], 10) : 0;

  return { prUrl, prNumber };
}

export async function mergePullRequest(
  prUrl: string,
  _config: AutoDevConfig,
): Promise<void> {
  await execa("gh", [
    "pr",
    "merge",
    prUrl,
    "--squash",
    "--delete-branch",
  ]);
}
