import { execa } from "execa";
import type { GitHubIssue, ReviewFinding } from "../machine/context.js";
import type { AutoDevConfig } from "../config/schema.js";

export async function createPullRequest(
  issue: GitHubIssue,
  config: AutoDevConfig,
  findings: ReviewFinding[],
): Promise<string> {
  const title = `feat: #${issue.number} — ${issue.title}`;

  const findingsSummary =
    findings.length > 0
      ? findings
          .map((f) => `- [${f.severity}] ${f.file}${f.line ? `:${f.line}` : ""}: ${f.description}`)
          .join("\n")
      : "No review findings.";

  const body = config.git.pr_template
    .replace("{summary}", `Implements issue #${issue.number}: ${issue.title}`)
    .replace("{issue_number}", String(issue.number))
    .concat(
      `\n\n## Review Findings Addressed\n${findingsSummary}\n\n---\n*Generated by AutoDev*`,
    );

  const result = await execa("gh", [
    "pr",
    "create",
    "--repo",
    config.repo,
    "--base",
    "main",
    "--title",
    title,
    "--body",
    body,
  ]);

  // gh pr create outputs the PR URL to stdout (or sometimes stderr)
  const prUrl = result.stdout.trim() || result.stderr.trim();
  if (!prUrl) {
    return `https://github.com/${config.repo}/pulls`;
  }

  // Extract URL if mixed with other output
  const urlMatch = prUrl.match(/https:\/\/github\.com\/[^\s]+/);
  const url = urlMatch ? urlMatch[0] : prUrl;

  // Auto-merge the PR and delete the branch
  try {
    await execa("gh", [
      "pr",
      "merge",
      url,
      "--squash",
      "--delete-branch",
    ]);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`  Warning: Auto-merge failed (${msg.slice(0, 80)}). PR is open for manual merge.`);
  }

  return url;
}
