import { z } from "zod/v4";

export const configSchema = z.object({
  repo: z
    .string()
    .regex(/^[^/]+\/[^/]+$/, "Must be in 'owner/repo' format"),

  issues: z.object({
    filter: z.object({
      labels: z.array(z.string()).min(1, "At least one label is required"),
      milestone: z.string().optional(),
    }),
    max_questions_per_issue: z.number().int().positive().default(5),
  }),

  reviewer: z.object({
    type: z.enum(["codex", "claude"]),
    max_iterations: z.number().int().min(1).max(10).default(3),
  }),

  git: z.object({
    branch_prefix: z.string().default("autodev"),
    commit_co_author: z.string().default("AutoDev Bot <autodev@local>"),
    pr_template: z.string().default(
      [
        "## Summary",
        "{summary}",
        "",
        "Closes #{issue_number}",
        "",
        "---",
        "*Generated by AutoDev*",
      ].join("\n"),
    ),
  }),

  telegram: z.object({
    chat_id: z.string(),
    escalation_timeout_minutes: z.number().int().positive().default(240),
    reminder_interval_minutes: z.number().int().positive().default(60),
  }),

  logging: z
    .object({
      level: z.enum(["debug", "info", "warn", "error"]).default("info"),
      dir: z.string().default("./logs"),
    })
    .default({ level: "info", dir: "./logs" }),

  executor: z
    .object({
      allowed_tools: z
        .array(z.string())
        .default(["Read", "Edit", "Write", "Bash", "Glob", "Grep"]),
      working_directory: z.string().default("."),
    })
    .default({
      allowed_tools: ["Read", "Edit", "Write", "Bash", "Glob", "Grep"],
      working_directory: ".",
    }),
});

export type AutoDevConfig = z.infer<typeof configSchema>;
