import readlineSync from "readline-sync";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { execa } from "execa";
import { stringify as yamlStringify } from "yaml";

const CYAN = "\x1b[36m";
const BOLD = "\x1b[1m";
const DIM = "\x1b[2m";
const RESET = "\x1b[0m";
const GREEN = "\x1b[32m";

function header(text: string): void {
  console.log(`\n${BOLD}${CYAN}${text}${RESET}`);
}

function hint(text: string): void {
  console.log(`${DIM}${text}${RESET}`);
}

/**
 * Interactive setup wizard — walks the user through creating an autodev.config.yaml
 * for the target repo. Returns the path to the created config file.
 */
export async function runSetup(configPath: string): Promise<string> {
  console.log(`\n${BOLD}${CYAN}╔══════════════════════════════════════╗`);
  console.log(`║       AutoDev Setup Wizard           ║`);
  console.log(`╚══════════════════════════════════════╝${RESET}\n`);

  const resolvedPath = resolve(configPath);
  const repoDir = dirname(resolvedPath);

  // 1. Repo
  header("1. GitHub Repository");
  let detectedRepo = "";
  try {
    const { stdout } = await execa("gh", ["repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"], { cwd: repoDir });
    detectedRepo = stdout.trim();
  } catch {
    // Not a gh-linked repo, ask manually
  }

  let repo: string;
  if (detectedRepo) {
    hint(`Detected: ${detectedRepo}`);
    const useDetected = readlineSync.keyInYNStrict(`Use ${detectedRepo}?`);
    if (useDetected) {
      repo = detectedRepo;
    } else {
      repo = readlineSync.question("Enter repo (owner/name): ");
    }
  } else {
    repo = readlineSync.question("Enter GitHub repo (owner/name): ");
  }

  // 2. Issue label filter
  header("2. Issue Filter");
  hint("AutoDev will only process issues with this label.");
  const label = readlineSync.question(`Label to filter by [${GREEN}autoDev${RESET}]: `, { defaultInput: "autoDev" });

  const useMilestone = readlineSync.keyInYNStrict("Filter by milestone too?");
  let milestone: string | undefined;
  if (useMilestone) {
    milestone = readlineSync.question("Milestone name: ");
  }

  const maxQuestions = readlineSync.questionInt(
    `Max Telegram questions per issue before skipping [${GREEN}5${RESET}]: `,
    { defaultInput: "5" },
  );

  // 3. Reviewer
  header("3. Code Reviewer");
  hint("The reviewer runs an independent session to check code quality.");
  const reviewerIdx = readlineSync.keyInSelect(["Claude (recommended)", "Codex (OpenAI)"], "Which reviewer?", { cancel: false });
  const reviewerType = reviewerIdx === 0 ? "claude" : "codex";
  const maxIterations = readlineSync.questionInt(
    `Max review iterations [${GREEN}3${RESET}]: `,
    { defaultInput: "3" },
  );

  // 4. Telegram
  header("4. Telegram Notifications");
  hint("Optional — used for question escalation when AI can't answer.");
  hint("Get your chat ID by messaging @userinfobot on Telegram.");
  const chatId = readlineSync.question(`Telegram chat ID [${DIM}skip${RESET}]: `, { defaultInput: "" });

  // 5. Build config
  header("5. Creating config file");

  const config: Record<string, unknown> = {
    repo,
    issues: {
      filter: {
        labels: [label],
        ...(milestone ? { milestone } : {}),
      },
      max_questions_per_issue: maxQuestions,
    },
    reviewer: {
      type: reviewerType,
      max_iterations: maxIterations,
    },
    git: {
      branch_prefix: "autodev",
      commit_co_author: "AutoDev Bot <autodev@local>",
      pr_template: "## Summary\n{summary}\n\nCloses #{issue_number}\n\n---\n*Generated by AutoDev*",
    },
    telegram: {
      chat_id: chatId || "NOT_CONFIGURED",
      escalation_timeout_minutes: 240,
      reminder_interval_minutes: 60,
    },
    logging: {
      level: "info",
      dir: "./logs",
    },
    executor: {
      allowed_tools: ["Read", "Edit", "Write", "Bash", "Glob", "Grep"],
      working_directory: ".",
    },
  };

  const yamlContent = `# AutoDev Configuration — generated by setup wizard\n# Secrets (API keys, bot tokens) go in .env — never in this file.\n\n${yamlStringify(config)}`;

  writeFileSync(resolvedPath, yamlContent, "utf-8");

  console.log(`\n${GREEN}✓${RESET} Config saved to: ${resolvedPath}`);
  console.log(`\n${DIM}You can edit this file anytime to change settings.${RESET}\n`);

  return resolvedPath;
}
